version: '3'

services:
  php-web60018:
    image: niclab/php8.1
    platform: linux/x86_64
    container_name: php-web60018
    working_dir: /var/www
    ports:
      - 60018:80
    volumes:
      - "./root:/var/www"
      - "./docker/php-web/php.ini:/usr/local/etc/php/php.ini"
      - "./docker/php-web/custom-vhost.conf:/etc/apache2/sites-available/000-default.conf"

  mysql60118:
    image: library/mysql:5.7
    platform: linux/x86_64
    container_name: mysql60118
    ports:
      - 60118:3306
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=toF9vDwj3F
      - MYSQL_DATABASE=a2public_copy_paste
      - MYSQL_USER=a2public
      - MYSQL_PASSWORD=toF9vDwj3F

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/x86_64
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql60118
      - PMA_USER=a2public
      - PMA_PASSWORD=toF9vDwj3F
    links:
      - mysql60118
    ports:
      - 60218:80
    volumes:
      - ./docker/phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
